### ISSUE TITLE
Issue running mvn test jetty:run

### ISSUE THREAD

**Issue by ravening** [davidmoten/websockets-log-tail#1]
Hello

I checkedout the git repo and when I run mvn test jetty:run, I get the below error. Is there any other dependencies I need to add?

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.326 s
[INFO] Finished at: 2019-04-04T14:13:12Z
[INFO] Final Memory: 19M/319M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.mortbay.jetty:jetty-maven-plugin:8.1.16.v20140903:run (default-cli) on project java-websockets: Execution default-cli of goal org.mortbay.jetty:jetty-maven-plugin:8.1.16.v20140903:run failed: Plugin org.mortbay.jetty:jetty-maven-plugin:8.1.16.v20140903 or one of its dependencies could not be resolved: The following artifacts could not be resolved: javax.jms:jms:jar:1.1, com.sun.jdmk:jmxtools:jar:1.2.1, com.sun.jmx:jmxri:jar:1.2.1: Could not transfer artifact javax.jms:jms:jar:1.1 from/to java.net (https://maven-repository.dev.java.net/nonav/repository): Cannot access https://maven-repository.dev.java.net/nonav/repository with type legacy using the available connector factories: BasicRepositoryConnectorFactory: Cannot access https://maven-repository.dev.java.net/nonav/repository with type legacy using the available layout factories: Maven2RepositoryLayoutFactory: Unsupported repository layout legacy -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginResolutionException

**Comment by davidmoten** [comment]
Thanks, looks like it's time to update the plugins. I'll have a look.

**Comment by davidmoten** [comment]
Hi should work now. I'll upgrade the jetty stuff and the rxjava stuff as well shortly.

**Comment by davidmoten** [comment]
I've also upgraded to use rxjava 2.x. Examples on README.md are working for me. Thanks for the report.
